language: java

jdk: openjdk8

branches:
  only: master

# Travis CI Server Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI message alram
notifications:
  email:
    recipients: shrkfl181@gmail.com 
    
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings value
    secret_access_key : $AWS_SECRET_KEY # Travis rep settings value
    bucket: springboot-webserivce-deploys # S3 Bucket
    region: ap-northeast-2
    skip-cleanup: true
    acl: public_read
    wait-until-deployed: true
    on:
      repo: kamui178/spring-webservice # github
      branch: master
    