spring:
  profiles:
    active: local
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
   
# local enviornment
---
spring:
  profiles: local
  
  datasource:
    # if you run script file location when it can start
    data: classpath:data-h2.sql 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true

#server:
#  port: 8083
  
---

spring:
  profiles: set1
  datasource:
    url: jdbc:mariadb://springbootservice.csbnohvfiz5i.ap-northeast-2.rds.amazonaws.com:3306/webservice
    username: hoya
    password: 'f0d50099'
    driver-class-name: org.mariadb.jdbc.Driver

spring.profiles.include: real-db

server:
  port: 8081
  
---

spring:
  profiles: set2
  datasource:
    url: jdbc:mariadb://springbootservice.csbnohvfiz5i.ap-northeast-2.rds.amazonaws.com:3306/webservice
    username: hoya
    password: 'f0d50099'
    driver-class-name: org.mariadb.jdbc.Driver

spring.profiles.include: real-db
  
server:
  port: 8082
  
