spring:
  profiles:
    active: local
   
# local enviornment
---
spring:
  profiles: local
  
  datasource:
    # if you run script file location when it can start
    data: classpath:data-h2.sql 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true

---

spring:
  profiles: set1

server:
  port: 8081
  
---

spring:
  profiles: set2
  
server:
  port: 8082
  
