spring:
  h2:
    console:
      enabled: true
#Encoding UTF-8
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# local enviornment
---
spring:
  profiles: local
  datasource:
    # if you run script file location when it can start
    data: classpath:data-h2.sql 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      
